// src/components/demos/interactive/0027.100-09.tsx
import { useEffect, useRef, useState } from 'react'

const charset = 'abcdefghijklmnopqrstuvwxyz'

export default function ScrambleButton({ label = 'Submit Form' }: { label?: string }) {
  const [displayText, setDisplayText] = useState(label)
  const timersRef = useRef<ReturnType<typeof setTimeout>[]>([])

  useEffect(() => {
    const timers = timersRef.current
    return () => {
      timers.forEach(clearTimeout)
      timers.length = 0
    }
  }, [])

  useEffect(() => {
    const frame = requestAnimationFrame(() => setDisplayText(label))
    return () => cancelAnimationFrame(frame)
  }, [label])

  function scramble() {
    timersRef.current.forEach(clearTimeout)
    timersRef.current.length = 0
    for (let index = 0; index < label.length; index++) {
      const timer = setTimeout(() => {
        const prefix = label.slice(0, index + 1)
        const random = Array.from({ length: label.length - prefix.length }, () => charset[Math.floor(Math.random() * charset.length)]).join('')
        setDisplayText(prefix + random)
      }, (index + 1) * 50)
      timersRef.current.push(timer)
    }
  }

  return (
    <button type="button" className="demo-scramble" onMouseEnter={scramble} onFocus={scramble}>
      {displayText}
      <style>
        {`
        .demo-scramble { border:1px solid #d1d5db; border-radius:8px; background:#fff; color:#111827; padding:16px 24px; font:600 20px ui-monospace,SFMono-Regular,monospace; box-shadow:0 1px 2px rgba(0,0,0,.06); cursor:pointer; }
        .demo-scramble:hover { background:#f9fafb; } .dark .demo-scramble { border-color:#4b5563; background:#1f2937; color:#fff; }
      `}
      </style>
    </button>
  )
}

// app/components/demos/0027.100-09.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{
  label?: string
}>(), {
  label: 'Submit Form',
})

const displayText = ref(props.label)
const charset = 'abcdefghijklmnopqrstuvwxyz'

function randomChars(length: number) {
  return Array.from({ length }).fill(charset[Math.floor(Math.random() * charset.length)]).join('')
}

async function scramble(input: string) {
  let prefix = ''
  for (let index = 0; index < input.length; index++) {
    await new Promise(resolve => setTimeout(resolve, 50))
    prefix += input.charAt(index)
    displayText.value = prefix + randomChars(input.length - prefix.length)
  }
}

function startScrambling() {
  scramble(props.label)
}

watch(
  () => props.label,
  (newValue) => {
    displayText.value = newValue
  },
)
</script>

<template>
  <CraftBox>
    <button
      type="button"
      class="rounded-md bg-white dark:bg-dark-800 px-6 py-4 text-xl font-semibold text-gray-900 dark:text-white shadow-sm ring-1 ring-inset ring-gray-300 dark:ring-gray-600 hover:bg-gray-50 dark:hover:bg-dark-900 relative font-mono"
      @mouseenter="startScrambling"
    >
      {{ displayText }}
    </button>
  </CraftBox>
</template>
