// app/components/demos/0015.craft-clipboard.vue
<script setup lang="ts">
const clipboard = ref<boolean>(false)

function switchClass() {
  clipboard.value = true
  setTimeout(() => {
    clipboard.value = false
  }, 2000)
}
</script>

<template>
  <CraftBox>
    <div class="flex justify-center items-center">
      <div
        class="clipboard w-8 h-8 p-2 scale-200 rounded-md cursor-pointer [transition:background_0.2s_ease] hover:[background:rgba(0,0,0,0.1)] dark:hover:[background:rgba(255,255,255,0.1)]"
        :class="[clipboard ? 'copied' : '']"
        @click="switchClass"
      >
        <svg
          class="op-90 [transition:opacity_0.2s_ease] hover:op-100"
          viewBox="0 0 16 32"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            class="[stroke-width:1.5] stroke-black fill-white dark:stroke-white dark:fill-black [stroke-linecap:round] [stroke-linejoin:round]"
            d="M3 12.75V4.25C3 3.42157 3.67157 2.75 4.5 2.75H12C12.8284 2.75 13.5 3.42157 13.5 4.25V12.75C13.5 13.5784 12.8284 14.25 12 14.25H4.5C3.67157 14.25 3 13.5784 3 12.75Z"
          />
          <path
            d="M3 12.75V4.25C3 3.42157 3.67157 2.75 4.5 2.75H12C12.8284 2.75 13.5 3.42157 13.5 4.25V12.75C13.5 13.5784 12.8284 14.25 12 14.25H4.5C3.67157 14.25 3 13.5784 3 12.75Z"
            class="[stroke-width:1.5] stroke-black fill-white dark:stroke-white dark:fill-black [stroke-linecap:round] [stroke-linejoin:round] origin-center"
            :class="[clipboard ? '[animation:copiedPage_2s_ease_forwards]' : '']"
          />
          <path
            d="M6.25 9.75L7.75 11.25L10.25 7.75"
            class="[stroke-width:1.5] fill-white dark:fill-black [stroke-linecap:round] [stroke-linejoin:round] origin-center stroke-#83F5AD [stroke-dasharray:8] [stroke-dashoffset:8] check"
            :class="[clipboard ? '[transition:all_.5s_ease] [animation:copiedPage_2s_ease_forwards]' : '']"
          />
          <path
            class="[stroke-width:1.5] stroke-black fill-white dark:stroke-white dark:fill-black [stroke-linecap:round] [stroke-linejoin:round]"
            d="M7 1.75001C6.72386 1.75001 6.5 1.97387 6.5 2.25001V3.5C6.5 4.4665 7.2835 5.25 8.25 5.25C9.2165 5.25 10 4.4665 10 3.5V2.25C10 1.97386 9.77614 1.75 9.5 1.75L7 1.75001Z"
          />
        </svg>
      </div>
    </div>
  </CraftBox>
</template>

<style>
@keyframes copiedPage {
  0% {
    transform: rotate(0) translateY(0);
    opacity: 1;
  }
  50% {
    transform: rotate(0) translateY(0);
    opacity: 1;
  }
  100% {
    transform: rotate(10deg) translateY(16px);
    opacity: 0;
  }
}
</style>

<style>
.clipboard.copied svg path.check {
  stroke-dasharray: 16;
}
</style>

// src/components/demos/interactive/0015.craft-clipboard.tsx
import { useEffect, useRef, useState } from 'react'

export default function CraftClipboard() {
  const [copied, setCopied] = useState(false)
  const timerRef = useRef<ReturnType<typeof setTimeout>>(undefined)

  useEffect(() => () => clearTimeout(timerRef.current), [])

  function animate() {
    clearTimeout(timerRef.current)
    setCopied(false)
    requestAnimationFrame(() => setCopied(true))
    timerRef.current = setTimeout(setCopied, 2000, false)
  }

  return (
    <button type="button" className={`demo-clipboard ${copied ? 'copied' : ''}`} aria-label="Copy" onClick={animate}>
      <svg viewBox="0 0 16 18" fill="none" aria-hidden="true">
        <path className="page" d="M3 14.5V6A1.5 1.5 0 0 1 4.5 4.5H12A1.5 1.5 0 0 1 13.5 6v8.5A1.5 1.5 0 0 1 12 16H4.5A1.5 1.5 0 0 1 3 14.5Z" />
        <path className="fall" d="M3 14.5V6A1.5 1.5 0 0 1 4.5 4.5H12A1.5 1.5 0 0 1 13.5 6v8.5A1.5 1.5 0 0 1 12 16H4.5A1.5 1.5 0 0 1 3 14.5Z" />
        <path className="check" d="m6.25 11.5 1.5 1.5 2.5-3.5" />
        <path className="clip" d="M7 3.5a.5.5 0 0 0-.5.5v1.25A1.75 1.75 0 0 0 8.25 7 1.75 1.75 0 0 0 10 5.25V4a.5.5 0 0 0-.5-.5H7Z" />
      </svg>
      <style>
        {`
        .demo-clipboard { width:48px; height:48px; padding:8px; border:0; border-radius:8px; background:transparent; color:#111; cursor:pointer; transition:background .2s; }
        .demo-clipboard:hover { background:rgba(0,0,0,.08); } .dark .demo-clipboard { color:#fff; } .dark .demo-clipboard:hover { background:rgba(255,255,255,.1); }
        .demo-clipboard svg { width:100%; height:100%; overflow:visible; } .demo-clipboard path { fill:transparent; stroke:currentColor; stroke-width:1.5; stroke-linecap:round; stroke-linejoin:round; transform-origin:center; }
        .demo-clipboard .check { stroke:#45d483; stroke-dasharray:8; stroke-dashoffset:8; }
        .demo-clipboard.copied .fall { animation:clipboard-fall 2s ease forwards; } .demo-clipboard.copied .check { animation:clipboard-check 2s ease forwards; }
        @keyframes clipboard-fall { 50% { transform:none; opacity:1; } 100% { transform:rotate(10deg) translateY(16px); opacity:0; } }
        @keyframes clipboard-check { 20% { stroke-dashoffset:8; } 45%,100% { stroke-dashoffset:0; } }
      `}
      </style>
    </button>
  )
}
