// app/components/demos/0023.100-05.vue
<!-- eslint-disable -->
<!-- prettier-ignore -->
<!-- @ts-nocheck -->
<script setup>
const colorMode = useColorMode()

onMounted(() => {
  nextTick(() => {
    const bgColor = ref(colorMode.preference ? '#1c1c1c' : '#f8f8f8')
    const canvas = document.getElementById('canvas')
    const ctx = canvas.getContext('2d')

    'floor|random|round|abs|sqrt|PI|atan2|sin|cos|pow|max|min|hypot'
      .split('|')
      .forEach((p) => { window[p] = Math[p] })

    const TAU = PI * 2

    function r(n) { return random() * n }
    function rrng(lo, hi) { return lo + r(hi - lo) }
    function rint(lo, hi) { return lo + floor(r(hi - lo + 1)) }
    function choose(args) { return args[rint(0, args.length - 1)] }

    /* --------------------------------------------------------------------------- */

    let W, H, frame, time, DPR

    function dpr(n) { return DPR * n }

    function resize() {
      const w = innerWidth
      const h = innerHeight
      DPR = devicePixelRatio || 1

      canvas.style.width = `${w}px`
      canvas.style.height = `${h}px`

      W = canvas.width = w * DPR
      H = canvas.height = h * DPR
    }

    function loop(t) {
      frame = requestAnimationFrame(loop)
      draw()
      time++
    }

    function pause() {
      cancelAnimationFrame(frame)
      frame = frame ? null : requestAnimationFrame(loop)
    }

    function reset() {
      cancelAnimationFrame(frame)
      resize()
      ctx.clearRect(0, 0, W, H)
      init()
      time = 0
      frame = requestAnimationFrame(loop)
    }

    /* --------------------------------------------------------------------------- */

    function Vector(x, y) {
      this.x = x
      this.y = y
    }

    Vector.add = function (a, b) { return new Vector(a.x + b.x, a.y + b.y) }
    Vector.sub = function (a, b) { return new Vector(a.x - b.x, a.y - b.y) }
    Vector.mul = function (a, n) { return new Vector(a.x * n, a.y * n) }
    Vector.div = function (a, n) { return new Vector(a.x / n, a.y / n) }

    Vector.prototype.clone = function () {
      return new Vector(this.x, this.y)
    }

    Vector.prototype.add = function (other) {
      this.x += other.x
      this.y += other.y
      return this
    }

    Vector.prototype.sub = function (other) {
      this.x -= other.x
      this.y -= other.y
      return this
    }

    Vector.prototype.mul = function (n) {
      this.x *= n
      this.y *= n
      return this
    }

    Vector.prototype.div = function (n) {
      this.x /= n
      this.y /= n
      return this
    }

    Vector.prototype.mag = function () {
      const x = this.x; const y = this.y
      return sqrt(x * x + y * y)
    }

    Vector.prototype.normalize = function () {
      return this.div(this.mag())
    }

    Vector.prototype.constrain = function (n) {
      const m = this.mag()
      return m > n ? this.mul(n / m) : this
    }

    Vector.prototype.zero = function () {
      this.x = 0
      this.y = 0
    }

    function vec(x, y) {
      return new Vector(x, y)
    }

    /* --------------------------------------------------------------------------- */

    function Particle(max, loc) {
      this.loc = loc
      this.vel = vec(0, 0)
      this.max = max
      this.acc = vec(0, 0)
    // this.relocate();
    }

    Particle.prototype.relocate = function () {
      this.loc = vec(rrng(L, R), rrng(T, B))
      const t = r(TAU)
      const m = this.max
      this.vel = vec(m * cos(t), m * sin(t))
    }

    Particle.prototype.applyForce = function (force) {
      this.acc.add(force)
    }

    Particle.prototype.follow = function (field) {
      const desired = field.forceAt(this.loc)
      const steer = Vector.sub(desired, this.vel)
      this.applyForce(steer.constrain(this.max * 0.8))
    }

    Particle.prototype.seekFriend = function () {
      const desired = Vector.sub(this.friend.loc, this.loc)
      const steer = Vector.sub(desired, this.vel)
      this.applyForce(steer.constrain(this.max * 0.35))
    }

    Particle.prototype.move = function (draw) {
      if (draw) {
        ctx.moveTo(this.loc.x, this.loc.y)
        this.vel.add(this.acc).constrain(this.max)
        this.loc.add(this.vel)
        ctx.lineTo(this.loc.x, this.loc.y)
      }
      else {
        this.vel.add(this.acc).constrain(this.max)
        this.loc.add(this.vel)
      }

      this.acc.zero()

      if (this.loc.x < L) { this.loc.x = L; this.vel.x *= -1 }
      if (this.loc.y < T) { this.loc.y = T; this.vel.y *= -1 }
      if (this.loc.x > R) { this.loc.x = R; this.vel.x *= -1 }
      if (this.loc.y > B) { this.loc.y = B; this.vel.y *= -1 }
    }

    /* --------------------------------------------------------------------------- */

    function Field(x, y, w, h, res) {
      this.x = x
      this.y = y
      this.w = w
      this.h = h
      this.res = res
      this.forces = []
      this.imax = ~~(w / res)
      this.jmax = ~~(h / res)
      for (let i = 0; i <= w / res; i++) {
        this.forces[i] = []
        for (let j = 0; j <= h / res; j++) {
          const t = r(TAU)
          const m = r(dpr(5))
          this.forces[i][j] = vec(cos(t), sin(t)).mul(m)
        }
      }
    }

    Field.prototype = {
      forceAt(v) {
        let i = ~~((v.x - this.x) / this.res)
        let j = ~~((v.y - this.y) / this.res)
        i = max(i, 0)
        i = min(i, this.imax)
        j = max(j, 0)
        j = min(j, this.jmax)
        return this.forces[i][j]
      },
      reset() {
        for (let i = 0; i <= this.imax; i++) {
          for (let j = 0; j <= this.jmax; j++) {
            const t = r(TAU)
            const m = r(dpr(5))
            this.forces[i][j] = vec(cos(t), sin(t)).mul(m)
          }
        }
      },
      perturb(n) {
        let ii, jj, t
        for (; n > 0; n--) {
          ii = rint(0, this.imax)
          jj = rint(0, this.jmax)
          t = r(TAU)
          this.forces[ii][jj] = vec(cos(t), sin(t)).mul(r(dpr(5)))
        }
      },
      draw() {
        const res = this.res
        ctx.save()
        for (let i = 0; i <= this.imax; i++) {
          for (let j = 0; j <= this.jmax; j++) {
            const force = Vector.mul(this.forces[i][j], dpr(3))
            const x = this.x + i * res + res / 2
            const y = this.y + j * res + res / 2
            ctx.moveTo(x, y)
            ctx.lineTo(x + force.x, y + force.y)
          }
        }
        ctx.strokeStyle = 'rgba(128, 128, 128, 1)'
        ctx.stroke()
        ctx.restore()
      },
    }

    /* --------------------------------------------------------------------------- */

    let P, particles
    let L, R, T, B
    let field

    const black = 'rgba(128, 128, 128, 1)'

    function init() {
      L = W / 2 - dpr(300)
      R = W / 2 + dpr(300)
      T = H / 2 - dpr(300)
      B = H / 2 + dpr(300)

      P = 14000
      particles = new Array(P)
      const n = dpr(150)

      for (var i = 0; i < P; i++) {
        //    var y = H/2-dpr(300)+i;
        const t = r(TAU)
        particles[i] = new Particle(dpr(3), vec(W / 2 + n * cos(t), H / 2 + n * sin(t)))
      }

      for (i = 1; i < P; i++)
        particles[i].friend = particles[i - 1]

      particles[0].friend = particles[P - 1]

      field = new Field(L, T, dpr(600), dpr(600), dpr(10))

      ctx.strokeStyle = black
    }

    function draw() {
    // if (time % 120 === 0) {
      // field.reset();
    // }
      field.perturb(20)
      ctx.fillStyle = bgColor.value
      ctx.fillRect(0, 0, W, H)
      ctx.beginPath()
      for (let i = 0; i < P; i++) {
        const p = particles[i]
        p.follow(field)
        p.seekFriend()
        p.move(true)
      }

      ctx.stroke()
    }

    /* --------------------------------------------------------------------------- */

    watch(colorMode.preference, () => {
      bgColor.value = colorMode.preference ? '#1c1c1c' : '#f8f8f8'
    })

    reset()
  })
})
</script>

<template>
  <CraftBox class="h-60!">
    <canvas id="canvas" />
  </CraftBox>
</template>

// src/components/demos/interactive/0023.100-05.tsx
import { useEffect, useRef } from 'react'

interface Particle { x: number, y: number, vx: number, vy: number }

export default function ParticleField() {
  const canvasRef = useRef<HTMLCanvasElement>(null)

  useEffect(() => {
    const canvas = canvasRef.current
    const parent = canvas?.parentElement
    const ctx = canvas?.getContext('2d')
    if (!canvas || !parent || !ctx)
      return
    let width = 1
    let height = 1
    let frame = 0
    let particles: Particle[] = []
    const resize = () => {
      const bounds = parent.getBoundingClientRect()
      const dpr = Math.min(window.devicePixelRatio || 1, 2)
      width = Math.max(1, bounds.width)
      height = Math.max(1, bounds.height)
      canvas.width = width * dpr
      canvas.height = height * dpr
      canvas.style.width = `${width}px`
      canvas.style.height = `${height}px`
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
      particles = Array.from({ length: 1800 }, (_, index) => {
        const angle = index / 1800 * Math.PI * 2 + Math.random() * 0.1
        const radius = Math.min(width, height) * (0.22 + Math.random() * 0.08)
        return { x: width / 2 + Math.cos(angle) * radius, y: height / 2 + Math.sin(angle) * radius, vx: 0, vy: 0 }
      })
    }
    const observer = new ResizeObserver(resize)
    observer.observe(parent)
    resize()
    const render = (now: number) => {
      ctx.fillStyle = document.documentElement.classList.contains('dark') ? '#1c1c1c' : '#f8f8f8'
      ctx.fillRect(0, 0, width, height)
      ctx.strokeStyle = 'rgba(128,128,128,.42)'
      ctx.lineWidth = 0.45
      ctx.beginPath()
      for (let index = 0; index < particles.length; index++) {
        const particle = particles[index]
        const friend = particles[(index + particles.length - 1) % particles.length]
        const oldX = particle.x
        const oldY = particle.y
        const fieldAngle = Math.sin(particle.x * 0.012 + now * 0.00018) * 2.2 + Math.cos(particle.y * 0.015 - now * 0.00013)
        particle.vx += Math.cos(fieldAngle) * 0.12 + (friend.x - particle.x) * 0.0009
        particle.vy += Math.sin(fieldAngle) * 0.12 + (friend.y - particle.y) * 0.0009
        const speed = Math.hypot(particle.vx, particle.vy) || 1
        if (speed > 2.4) {
          particle.vx *= 2.4 / speed
          particle.vy *= 2.4 / speed
        }
        particle.x += particle.vx
        particle.y += particle.vy
        if (particle.x < 0 || particle.x > width) {
          particle.vx *= -1
          particle.x = Math.max(0, Math.min(width, particle.x))
        }
        if (particle.y < 0 || particle.y > height) {
          particle.vy *= -1
          particle.y = Math.max(0, Math.min(height, particle.y))
        }
        ctx.moveTo(oldX, oldY)
        ctx.lineTo(particle.x, particle.y)
      }
      ctx.stroke()
      frame = requestAnimationFrame(render)
    }
    frame = requestAnimationFrame(render)
    return () => {
      cancelAnimationFrame(frame)
      observer.disconnect()
    }
  }, [])

  return <canvas ref={canvasRef} aria-label="Animated particle field" style={{ width: '100%', height: '100%' }} />
}
