// app/components/demos/0037.100-19.vue
<script setup lang="ts">
const formRef = ref<HTMLFormElement | null>(null)

formRef.value?.addEventListener('submit', (event) => {
  event.preventDefault()
})
</script>

<template>
  <CraftBox>
    <form ref="formRef" action="#">
      <div class="error-email-form-group">
        <label for="input">
          <span style="--char-index: 0;" aria-hidden="true">E</span>
          <span style="--char-index: 1;" aria-hidden="true">m</span>
          <span style="--char-index: 2;" aria-hidden="true">a</span>
          <span style="--char-index: 3;" aria-hidden="true">i</span>
          <span style="--char-index: 4;" aria-hidden="true">l</span>
          <span class="sr-only">Email</span>
        </label>
        <input type="email" required>
      </div>
    </form>
  </CraftBox>
</template>

<style scoped>
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}

.error-email-form-group {
  --valid: hsl(145 50% 55%);
  --invalid: hsl(15 80% 55%);
  --transition: 0.2s;
  --color: hsl(268 1% 55%);
  display: grid;
  gap: 0.5rem;
}

label {
  display: flex;
  color: var(--color);
  transition: color var(--transition);
  letter-spacing: 0.1ch;
  padding-left: 0.5rem;
  font-weight: bold;
}

label > [aria-hidden] {
  animation-duration: 0.2s;
  animation-delay: calc(var(--char-index) * 0.1s);
  animation-fill-mode: both;
  animation-timing-function: ease-in;
}

@keyframes jump {
  50% {
    translate: 0 -50%;
  }
}

@keyframes shake {
  25% {
    translate: 0.25ch 0;
  }
  75% {
    translate: -0.25ch 0;
  }
}

input {
  --at-apply: dark:text-dark text-light;
  padding: 0.5rem;
  border-radius: 0.5rem;
  border: 0.2rem solid var(--color);
  transition: border var(--transition);
}

.error-email-form-group:has(:user-valid) {
  --color: var(--valid);
}

.error-email-form-group:not(:focus-within):has(:user-invalid) {
  --color: var(--invalid);
}

@media (prefers-reduced-motion: no-preference) {
  .error-email-form-group:not(:focus-within):has(:user-valid) [aria-hidden] {
    animation-name: jump;
  }

  .error-email-form-group:not(:focus-within):has(:user-invalid) label {
    animation: shake 0.075s 8;
  }
}
</style>

// src/components/demos/interactive/0037.100-19.tsx
import type { CSSProperties } from 'react'

export default function EmailValidation() {
  return (
    <form className="demo-email" onSubmit={event => event.preventDefault()}>
      <label htmlFor="demo-email-input">
        <span aria-hidden="true" style={{ '--char-index': 0 } as CSSProperties}>E</span>
        <span aria-hidden="true" style={{ '--char-index': 1 } as CSSProperties}>m</span>
        <span aria-hidden="true" style={{ '--char-index': 2 } as CSSProperties}>a</span>
        <span aria-hidden="true" style={{ '--char-index': 3 } as CSSProperties}>i</span>
        <span aria-hidden="true" style={{ '--char-index': 4 } as CSSProperties}>l</span>
        <span className="sr-only">Email</span>
      </label>
      <input id="demo-email-input" type="email" required />
      <style>
        {`
        .demo-email { --valid:hsl(145 50% 55%); --invalid:hsl(15 80% 55%); --color:hsl(268 1% 55%); display:grid; gap:.5rem; }
        .demo-email label { display:flex; color:var(--color); transition:color .2s; letter-spacing:.1ch; padding-left:.5rem; font-weight:700; }
        .demo-email label>[aria-hidden] { animation-duration:.2s; animation-delay:calc(var(--char-index) * .1s); animation-fill-mode:both; }
        .demo-email input { min-width:250px; padding:.5rem; border-radius:.5rem; border:.2rem solid var(--color); background:white; color:#111; outline:none; transition:border .2s; }
        .dark .demo-email input { background:#111; color:#fff; }
        .demo-email:has(input:user-valid) { --color:var(--valid); } .demo-email:not(:focus-within):has(input:user-invalid) { --color:var(--invalid); }
        .demo-email:not(:focus-within):has(input:user-valid) [aria-hidden] { animation-name:email-jump; }
        .demo-email:not(:focus-within):has(input:user-invalid) label { animation:email-shake .075s 8; }
        .demo-email .sr-only { position:absolute; width:1px; height:1px; padding:0; margin:-1px; overflow:hidden; clip:rect(0,0,0,0); white-space:nowrap; }
        @keyframes email-jump { 50% { translate:0 -50%; } } @keyframes email-shake { 25% { translate:.25ch 0; } 75% { translate:-.25ch 0; } }
      `}
      </style>
    </form>
  )
}
