// app/components/demos/0035.100-17.vue
<script setup lang="ts">

</script>

<template>
  <CraftBox class="h-60!">
    <div class="absolute left-1/2 top-1/2">
      <b
        v-for="i in 15"
        :key="i"
        class="absolute block rotate-[-10deg] rounded-1/20"
        :style="{
          width: `${i * 10}px`,
          height: `${i * 10}px`,
          left: `-${i * 5}px`,
          top: `-${i * 5}px`,
          filter: `blur(${i * 0.15}px)`,
          boxShadow: `0 0 ${i * 1}px var(--color-wiggle)`,
          animation: `wiggle 0.4s cubic-bezier(0.445, 0.05, 0.55, 0.95) ${50 * i}ms infinite alternate`,
        }"
      />
    </div>
  </CraftBox>
</template>

<style>
.dark:root{
  --color-wiggle: rgba(255, 255, 255, 0.5);
}
:root {
  --color-wiggle: rgba(0, 0, 0, 0.9);
}
@keyframes wiggle {
  0% {
    transform: rotate(-10deg);
 }
  100% {
    transform: rotate(10deg);
 }
}
</style>

// src/components/demos/static-a/0035.100-17.tsx
import './0035.100-17.css'

export default function WiggleDemo() {
  return (
    <div className="demo0035-wiggle" aria-label="Wiggling concentric squares">
      {Array.from({ length: 15 }, (_, index) => {
        const number = index + 1
        return (
          <b
            key={number}
            style={{
              animationDelay: `${50 * number}ms`,
              boxShadow: `0 0 ${number}px var(--demo0035-color)`,
              filter: `blur(${number * 0.15}px)`,
              height: `${number * 10}px`,
              left: `${-number * 5}px`,
              top: `${-number * 5}px`,
              width: `${number * 10}px`,
            }}
          />
        )
      })}
    </div>
  )
}
